# permissions for end users to edit ibmlicenseservicereporters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ibmlicenseservicereporter-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-license-service-reporter-operator
    app.kubernetes.io/part-of: ibm-license-service-reporter-operator
    app.kubernetes.io/managed-by: kustomize
  name: ibmlicenseservicereporter-editor-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - ibmlicenseservicereporters
  - ibmlicenseservicereporters/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
