apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: ibm-license-service-reporter
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-license-service-reporter-operator
    app.kubernetes.io/part-of: ibm-license-service-reporter-operator
    app.kubernetes.io/managed-by: kustomize
  name: ibm-license-service-reporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-license-service-reporter
subjects:
  - kind: ServiceAccount
    name: ibm-license-service-reporter
    namespace: ibm-licensing
