apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: ibm-license-service-reporter-operator
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-license-service-reporter-operator
    app.kubernetes.io/part-of: ibm-license-service-reporter-operator
    app.kubernetes.io/managed-by: kustomize
  name: ibm-license-service-reporter-operator
  namespace: ibm-licensing
