//
// Copyright 2023 IBM Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

package secrets

import (
	"fmt"

	"github.com/go-logr/logr"
	. "github.ibm.com/cloud-license-reporter/ibm-license-service-reporter-operator/controllers/resources"
	"github.ibm.com/cloud-license-reporter/ibm-license-service-reporter-operator/controllers/resources/services"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

func ReconcileInternalCertificateSecret(logger logr.Logger, config IBMLicenseServiceReporterConfig) error {
	instance := config.Instance

	// Reconcile internal certificate only when no ServiceCA is present and certificate must be generated by us
	if !config.IsServiceCAAPI {
		hosts := make([]string, 2)
		hosts[0] = fmt.Sprintf("%s.%s.svc", LicenseReporterResourceBase, instance.Namespace)
		hosts[1] = fmt.Sprintf("%s.%s.svc.cluster.local", LicenseReporterResourceBase, instance.Namespace)

		expectedSecret := corev1.Secret{
			ObjectMeta: metav1.ObjectMeta{
				Name:        services.InternalCertSecretName,
				Namespace:   instance.GetNamespace(),
				Labels:      LabelsForMeta(instance),
				Annotations: GetSpecAnnotations(instance),
			},
		}
		logger = AddResourceValuesToLog(logger, &expectedSecret)
		return ReconcileResource(
			config,
			&expectedSecret,
			&corev1.Secret{},
			true,
			func(expected ExpectedObject) (ExpectedObject, error) {
				return overrideInternalCertExpectedSecret(logger, config, hosts, expected)
			},
			func(config IBMLicenseServiceReporterConfig, found FoundObject, expected ExpectedObject, logger logr.Logger) (ResourceUpdateStatus, error) {
				foundSecret := found.(*corev1.Secret)
				expectedSecret := expected.(*corev1.Secret)
				return IsSecretCertificateInDesiredState(config, logger, *foundSecret, *expectedSecret, hosts)
			},
			PatchFoundWithSpecLabelsAndAnnotations,
			func(found FoundObject, expected ExpectedObject) (client.Object, bool, error) {
				overriddenExpected, err := overrideInternalCertExpectedSecret(logger, config, hosts, expected)
				if err != nil {
					return nil, false, err
				}
				return overriddenExpected, false, nil
			},
			logger,
			nil,
		)
	}

	return nil
}

func overrideInternalCertExpectedSecret(logger logr.Logger, config IBMLicenseServiceReporterConfig, hosts []string, expected ExpectedObject) (ExpectedObject, error) {
	expectedSecret, err := getSelfSignedCertWithOwnerReference(logger, config, types.NamespacedName{
		Namespace: expected.GetNamespace(),
		Name:      expected.GetName(),
	}, hosts)
	if err != nil {
		return nil, fmt.Errorf("error generating internal self-signed certificate: %v", err)
	}
	return expectedSecret, nil
}
