apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: ibm-license-service-reporter-operator
    app.kubernetes.io/name: namespace
    app.kubernetes.io/instance: ibm-licensing
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: ibm-license-service-reporter-operator
    app.kubernetes.io/part-of: ibm-license-service-reporter-operator
    app.kubernetes.io/managed-by: kustomize
  name: ibm-licensing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibm-license-service-reporter-operator
  namespace: ibm-licensing
  labels:
    control-plane: ibm-license-service-reporter-operator
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: ibm-license-service-reporter-operator
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: ibm-license-service-reporter-operator
    app.kubernetes.io/part-of: ibm-license-service-reporter-operator
    app.kubernetes.io/managed-by: kustomize
  annotations:
    productID: 068a62892a1e4db39641342e592daa25
    productMetric: FREE
    productName: IBM Cloud Platform Common Services
spec:
  selector:
    matchLabels:
      control-plane: ibm-license-service-reporter-operator
  replicas: 1
  template:
    metadata:
      annotations:
        productID: 068a62892a1e4db39641342e592daa25
        productMetric: FREE
        productName: IBM Cloud Platform Common Services
        kubectl.kubernetes.io/default-container: ibm-license-service-reporter-operator
      labels:
        app.kubernetes.io/instance: ibm-license-service-reporter-operator
        app.kubernetes.io/managed-by: ibm-license-service-reporter-operator
        app.kubernetes.io/name: ibm-license-service-reporter
        name: ibm-license-service-reporter-operator
        control-plane: ibm-license-service-reporter-operator
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
                - key: kubernetes.io/os
                  operator: In
                  values:
                    - linux
      containers:
      - command:
        - ibm-license-service-reporter-operator
        env:
        - name: IBM_POSTGRESQL_IMAGE
          value: icr.io/cpopen/cpfs/ibm-postgresql:4.2.12
        - name: IBM_LICENSE_SERVICE_REPORTER_IMAGE
          value: icr.io/cpopen/cpfs/ibm-license-service-reporter:4.2.12
        - name: IBM_LICENSE_SERVICE_REPORTER_UI_IMAGE
          value: icr.io/cpopen/cpfs/ibm-license-service-reporter-ui:4.2.12
        - name: IBM_LICENSE_SERVICE_REPORTER_AUTH_IMAGE
          value: icr.io/cpopen/cpfs/ibm-license-service-reporter-oauth2-proxy:4.2.12
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.annotations['olm.targetNamespaces']
        - name: OPERATOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: ibm-license-service-reporter-operator
        - name: SA_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        args:
        - --leader-elect
        image: icr.io/cpopen/ibm-license-service-reporter-operator:4.2.12
        name: ibm-license-service-reporter-operator
        imagePullPolicy: IfNotPresent
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          limits:
            cpu: 10m
            memory: 64Mi
            ephemeral-storage: 500Mi
          requests:
            cpu: 10m
            memory: 64Mi
            ephemeral-storage: 256Mi
      serviceAccountName: ibm-license-service-reporter-operator
