# permissions for end users to edit namespacescopes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacescope-editor-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - namespacescopes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - namespacescopes/status
  verbs:
  - get
