# permissions for end users to view namespacescopes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacescope-viewer-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - namespacescopes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - namespacescopes/status
  verbs:
  - get
