---
apiVersion: operator.ibm.com/v1
kind: IBMLicenseServiceScanner
metadata:
  labels:
    app.kubernetes.io/name: ibm-licensing-scanner-instance
    app.kubernetes.io/instance: ibm-licensing-scanner-instance
    app.kubernetes.io/part-of: ibm-licensing-scanner-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: ibm-licensing-scanner-operator
  name: ibm-licensing-scanner-instance
spec:
  license-service-upload-secret: "ibm-licensing-scanner-upload-secret"
  registry-pull-secret: "ibm-licensing-scanner-registry-pull-secret"
  log-level: "INFO"
  license:
    accept:
      false
  scan: 
    namespaces: []