apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operand-deployment-lifecycle-manager-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operand-deployment-lifecycle-manager-leader-election-role
subjects:
- kind: ServiceAccount
  name: operand-deployment-lifecycle-manager
  namespace: system
