# permissions for end users to view operandconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operandconfig-viewer-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - operandconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - operandconfigs/status
  verbs:
  - get
