# permissions for end users to edit operandbindinfoes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operandbindinfo-editor-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - operandbindinfoes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - operandbindinfoes/status
  verbs:
  - get
