# permissions for end users to view operandregistries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operandregistry-viewer-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - operandregistries
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - operandregistries/status
  verbs:
  - get
