# permissions for end users to edit operandconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operandconfig-editor-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - operandconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - operandconfigs/status
  verbs:
  - get
