resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- newTag: 4.2.12
- name: controller
  newName: icr.io/cpopen/ibm-license-service-scanner-operator
  newTag: 4.2.12
