---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operand-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - update
  - apiGroups:
      - ""
    resources:
      - pods
      - namespaces
    verbs:
      - get
      - list
