---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/instance: operand-role-binding
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-licensing-scanner-operator
    app.kubernetes.io/part-of: ibm-licensing-scanner-operator
    app.kubernetes.io/managed-by: kustomize
  name: operand-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-licensing-scanner-operand-role
subjects:
  - kind: ServiceAccount
    name: ibm-licensing-scanner-operand-service-account
