---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/instance: operator-service-account
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-licensing-scanner-operator
    app.kubernetes.io/part-of: ibm-licensing-scanner-operator
    app.kubernetes.io/managed-by: kustomize
  name: operator-service-account
